version: 2

updates:
  # 1. GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  # 2. Python (uv)
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly

  # 3. Frontend (bun)
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly

  # 4. Docker Backend
  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly

  # 5. Docker Frontend
  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly