// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CompletenessStatsSchema = {
    properties: {
        host_star: {
            type: 'number',
            title: 'Host Star'
        },
        discovery_year: {
            type: 'number',
            title: 'Discovery Year'
        },
        discovery_method: {
            type: 'number',
            title: 'Discovery Method'
        },
        planet_radius: {
            type: 'number',
            title: 'Planet Radius'
        },
        planet_mass: {
            type: 'number',
            title: 'Planet Mass'
        },
        planet_density: {
            type: 'number',
            title: 'Planet Density'
        },
        equilibrium_temperature: {
            type: 'number',
            title: 'Equilibrium Temperature'
        },
        incident_flux: {
            type: 'number',
            title: 'Incident Flux'
        },
        orbital_period: {
            type: 'number',
            title: 'Orbital Period'
        },
        semi_major_axis: {
            type: 'number',
            title: 'Semi Major Axis'
        },
        orbital_eccentricity: {
            type: 'number',
            title: 'Orbital Eccentricity'
        },
        stellar_effective_temperature: {
            type: 'number',
            title: 'Stellar Effective Temperature'
        },
        stellar_radius: {
            type: 'number',
            title: 'Stellar Radius'
        },
        stellar_mass: {
            type: 'number',
            title: 'Stellar Mass'
        },
        stellar_luminosity: {
            type: 'number',
            title: 'Stellar Luminosity'
        },
        stellar_age: {
            type: 'number',
            title: 'Stellar Age'
        },
        distance_from_earth: {
            type: 'number',
            title: 'Distance From Earth'
        },
        system_planet_count: {
            type: 'number',
            title: 'System Planet Count'
        },
        system_star_count: {
            type: 'number',
            title: 'System Star Count'
        },
        planet_class: {
            type: 'number',
            title: 'Planet Class'
        },
        planet_class_confidence: {
            type: 'number',
            title: 'Planet Class Confidence'
        },
        composition: {
            type: 'number',
            title: 'Composition'
        },
        composition_confidence: {
            type: 'number',
            title: 'Composition Confidence'
        },
        habitability_score: {
            type: 'number',
            title: 'Habitability Score'
        },
        habitability_confidence: {
            type: 'number',
            title: 'Habitability Confidence'
        }
    },
    type: 'object',
    required: ['host_star', 'discovery_year', 'discovery_method', 'planet_radius', 'planet_mass', 'planet_density', 'equilibrium_temperature', 'incident_flux', 'orbital_period', 'semi_major_axis', 'orbital_eccentricity', 'stellar_effective_temperature', 'stellar_radius', 'stellar_mass', 'stellar_luminosity', 'stellar_age', 'distance_from_earth', 'system_planet_count', 'system_star_count', 'planet_class', 'planet_class_confidence', 'composition', 'composition_confidence', 'habitability_score', 'habitability_confidence'],
    title: 'CompletenessStats'
} as const;

export const CompositionStatsSchema = {
    properties: {
        by_composition: {
            additionalProperties: {
                type: 'integer'
            },
            propertyNames: {
                '$ref': '#/components/schemas/PlanetComposition'
            },
            type: 'object',
            title: 'By Composition'
        },
        average_confidence: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Average Confidence'
        }
    },
    type: 'object',
    required: ['by_composition'],
    title: 'CompositionStats'
} as const;

export const ETLConfigSchema = {
    properties: {
        limit: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Limit',
            description: 'Max number of records to extract. None = no limit'
        },
        dry_run: {
            type: 'boolean',
            title: 'Dry Run',
            default: false
        },
        persist_run: {
            type: 'boolean',
            title: 'Persist Run',
            default: true
        },
        load_mode: {
            '$ref': '#/components/schemas/LoadMode',
            default: 'upsert'
        }
    },
    type: 'object',
    title: 'ETLConfig'
} as const;

export const ExoplanetFieldSchema = {
    type: 'string',
    enum: ['planet_name', 'host_star', 'discovery_year', 'discovery_method', 'planet_radius', 'planet_mass', 'planet_density', 'equilibrium_temperature', 'incident_flux', 'orbital_period', 'semi_major_axis', 'orbital_eccentricity', 'stellar_effective_temperature', 'stellar_radius', 'stellar_mass', 'stellar_luminosity', 'stellar_age', 'distance_from_earth', 'system_planet_count', 'system_star_count', 'planet_class', 'planet_class_confidence', 'composition', 'composition_confidence', 'habitability_score', 'habitability_confidence', 'photo_url'],
    title: 'ExoplanetField'
} as const;

export const ExoplanetFiltersSchema = {
    properties: {
        planet_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Planet Name'
        },
        host_star: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Host Star'
        },
        discovery_method: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discovery Method'
        },
        discovery_year: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discovery Year'
        },
        min_discovery_year: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Discovery Year'
        },
        max_discovery_year: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Discovery Year'
        },
        min_orbital_period: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Orbital Period'
        },
        max_orbital_period: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Orbital Period'
        },
        min_planet_radius: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Planet Radius'
        },
        max_planet_radius: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Planet Radius'
        },
        min_planet_mass: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Planet Mass'
        },
        max_planet_mass: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Planet Mass'
        },
        planet_class: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PlanetClass'
                },
                {
                    type: 'null'
                }
            ]
        },
        min_planet_class_confidence: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Planet Class Confidence'
        },
        max_planet_class_confidence: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Planet Class Confidence'
        },
        composition: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PlanetComposition'
                },
                {
                    type: 'null'
                }
            ]
        },
        min_composition_confidence: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Composition Confidence'
        },
        max_composition_confidence: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Composition Confidence'
        },
        min_habitability_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Habitability Score'
        },
        max_habitability_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Habitability Score'
        },
        min_habitability_confidence: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Habitability Confidence'
        },
        max_habitability_confidence: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Habitability Confidence'
        },
        min_distance_from_earth: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Distance From Earth'
        },
        max_distance_from_earth: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Distance From Earth'
        },
        min_equilibrium_temperature: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Equilibrium Temperature'
        },
        max_equilibrium_temperature: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Equilibrium Temperature'
        },
        system_planet_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'System Planet Count'
        },
        min_system_planet_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min System Planet Count'
        },
        min_orbital_eccentricity: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Orbital Eccentricity'
        },
        max_orbital_eccentricity: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Orbital Eccentricity'
        },
        has_nasa_photo: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Has Nasa Photo'
        },
        sort_by: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ExoplanetSortField'
                },
                {
                    type: 'null'
                }
            ]
        },
        order: {
            '$ref': '#/components/schemas/SortOrder',
            default: 'asc'
        }
    },
    type: 'object',
    title: 'ExoplanetFilters'
} as const;

export const ExoplanetPublicSchema = {
    properties: {
        planet_name: {
            type: 'string',
            title: 'Planet Name'
        },
        host_star: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Host Star'
        },
        discovery_year: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discovery Year'
        },
        discovery_method: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discovery Method'
        },
        planet_radius: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Planet Radius'
        },
        planet_mass: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Planet Mass'
        },
        planet_density: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Planet Density'
        },
        equilibrium_temperature: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Equilibrium Temperature'
        },
        incident_flux: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Incident Flux'
        },
        orbital_period: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Orbital Period'
        },
        semi_major_axis: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Semi Major Axis'
        },
        orbital_eccentricity: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Orbital Eccentricity'
        },
        stellar_effective_temperature: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stellar Effective Temperature'
        },
        stellar_radius: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stellar Radius'
        },
        stellar_mass: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stellar Mass'
        },
        stellar_luminosity: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stellar Luminosity'
        },
        stellar_age: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stellar Age'
        },
        distance_from_earth: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Distance From Earth'
        },
        system_planet_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'System Planet Count'
        },
        system_star_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'System Star Count'
        },
        planet_class: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PlanetClass'
                },
                {
                    type: 'null'
                }
            ]
        },
        planet_class_confidence: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Planet Class Confidence'
        },
        composition: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PlanetComposition'
                },
                {
                    type: 'null'
                }
            ]
        },
        composition_confidence: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Composition Confidence'
        },
        habitability_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Habitability Score'
        },
        habitability_confidence: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Habitability Confidence'
        },
        photo_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Photo Url'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['planet_name', 'id'],
    title: 'ExoplanetPublic'
} as const;

export const ExoplanetQueryMetadataSchema = {
    properties: {
        count: {
            type: 'integer',
            title: 'Count'
        },
        returned: {
            type: 'integer',
            title: 'Returned'
        },
        skip: {
            type: 'integer',
            title: 'Skip'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        },
        sort_by: {
            '$ref': '#/components/schemas/ExoplanetSortField'
        },
        order: {
            '$ref': '#/components/schemas/SortOrder'
        },
        fields: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/ExoplanetField'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fields'
        },
        filters: {
            '$ref': '#/components/schemas/ExoplanetFilters'
        }
    },
    type: 'object',
    required: ['count', 'returned', 'skip', 'limit', 'sort_by', 'order', 'filters'],
    title: 'ExoplanetQueryMetadata'
} as const;

export const ExoplanetSortFieldSchema = {
    type: 'string',
    enum: ['planet_name', 'host_star', 'discovery_year', 'discovery_method', 'planet_radius', 'planet_mass', 'planet_density', 'equilibrium_temperature', 'incident_flux', 'orbital_period', 'semi_major_axis', 'orbital_eccentricity', 'stellar_effective_temperature', 'stellar_radius', 'stellar_mass', 'stellar_luminosity', 'stellar_age', 'distance_from_earth', 'system_planet_count', 'system_star_count', 'planet_class', 'planet_class_confidence', 'composition', 'composition_confidence', 'habitability_score', 'habitability_confidence'],
    title: 'ExoplanetSortField'
} as const;

export const ExoplanetStatsSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        by_method: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'By Method'
        },
        by_decade: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'By Decade'
        },
        planet_class: {
            '$ref': '#/components/schemas/PlanetClassStats'
        },
        composition: {
            '$ref': '#/components/schemas/CompositionStats'
        },
        habitability: {
            '$ref': '#/components/schemas/HabitabilityStats'
        },
        radius: {
            '$ref': '#/components/schemas/SummaryStats'
        },
        mass: {
            '$ref': '#/components/schemas/SummaryStats'
        },
        density: {
            '$ref': '#/components/schemas/SummaryStats'
        },
        equilibrium_temperature: {
            '$ref': '#/components/schemas/SummaryStats'
        },
        orbital_period: {
            '$ref': '#/components/schemas/SummaryStats'
        },
        distance: {
            '$ref': '#/components/schemas/SummaryStats'
        },
        completeness: {
            '$ref': '#/components/schemas/CompletenessStats'
        }
    },
    type: 'object',
    required: ['total', 'by_method', 'by_decade', 'planet_class', 'composition', 'habitability', 'radius', 'mass', 'density', 'equilibrium_temperature', 'orbital_period', 'distance', 'completeness'],
    title: 'ExoplanetStats'
} as const;

export const ExoplanetsQueryResponseSchema = {
    properties: {
        data: {
            items: {},
            type: 'array',
            title: 'Data'
        },
        meta: {
            '$ref': '#/components/schemas/ExoplanetQueryMetadata'
        }
    },
    type: 'object',
    required: ['data', 'meta'],
    title: 'ExoplanetsQueryResponse'
} as const;

export const ExportFormatSchema = {
    type: 'string',
    enum: ['csv', 'json', 'parquet'],
    title: 'ExportFormat'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HabitabilityStatsSchema = {
    properties: {
        average: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Average'
        },
        minimum: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Minimum'
        },
        maximum: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maximum'
        },
        average_confidence: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Average Confidence'
        },
        potentially_habitable: {
            type: 'integer',
            title: 'Potentially Habitable',
            default: 0
        }
    },
    type: 'object',
    title: 'HabitabilityStats'
} as const;

export const LoadModeSchema = {
    type: 'string',
    enum: ['upsert', 'insert', 'reload'],
    title: 'LoadMode'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PlanetClassSchema = {
    type: 'string',
    enum: ['Terrestrial', 'Super Earth', 'Sub-Neptune', 'Neptune', 'Ice Giant', 'Gas Giant', 'Unknown'],
    title: 'PlanetClass'
} as const;

export const PlanetClassStatsSchema = {
    properties: {
        by_class: {
            additionalProperties: {
                type: 'integer'
            },
            propertyNames: {
                '$ref': '#/components/schemas/PlanetClass'
            },
            type: 'object',
            title: 'By Class'
        },
        average_confidence: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Average Confidence'
        }
    },
    type: 'object',
    required: ['by_class'],
    title: 'PlanetClassStats'
} as const;

export const PlanetCompositionSchema = {
    type: 'string',
    enum: ['Rocky', 'Rocky-Iron', 'Water World', 'Ice', 'Hydrogen-Helium', 'Unknown'],
    title: 'PlanetComposition'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const SchedulerUpdateSchema = {
    properties: {
        interval_seconds: {
            type: 'integer',
            exclusiveMinimum: 59,
            title: 'Interval Seconds'
        }
    },
    type: 'object',
    required: ['interval_seconds'],
    title: 'SchedulerUpdate'
} as const;

export const SortOrderSchema = {
    type: 'string',
    enum: ['asc', 'desc'],
    title: 'SortOrder'
} as const;

export const SummaryStatsSchema = {
    properties: {
        average: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Average'
        },
        minimum: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Minimum'
        },
        maximum: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maximum'
        }
    },
    type: 'object',
    title: 'SummaryStats'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;