// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { MetricsResponse, EtlRunExoplanetEtlData, EtlRunExoplanetEtlResponse, EtlCrashResponse, ExoplanetsReadExoplanetsData, ExoplanetsReadExoplanetsResponse, ExoplanetsGetExoplanetStatsData, ExoplanetsGetExoplanetStatsResponse, ExoplanetsReadExoplanetByIdData, ExoplanetsReadExoplanetByIdResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlData, LoginRecoverPasswordHtmlResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserData, UsersReadUserResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class DefaultService {
    /**
     * Metrics
     * Endpoint that serves Prometheus metrics.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static metrics(): CancelablePromise<MetricsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/metrics'
        });
    }
}

export class EtlService {
    /**
     * Run Exoplanet Etl
     * Run ETL process for exoplanets (superuser only)
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static runExoplanetEtl(data: EtlRunExoplanetEtlData): CancelablePromise<EtlRunExoplanetEtlResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/etl/run',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Crash
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static crash(): CancelablePromise<EtlCrashResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/etl/crash'
        });
    }
}

export class ExoplanetsService {
    /**
     * Read Exoplanets
     * Retrieve a list of exoplanets with optional filters.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.planetName
     * @param data.hostStar
     * @param data.discoveryMethod
     * @param data.discoveryYear
     * @param data.minDiscoveryYear
     * @param data.maxDiscoveryYear
     * @param data.minOrbitalPeriod
     * @param data.maxOrbitalPeriod
     * @param data.minPlanetRadius
     * @param data.maxPlanetRadius
     * @param data.minPlanetMass
     * @param data.maxPlanetMass
     * @param data.composition
     * @param data.minCompositionConfidence
     * @param data.minHabitabilityScore
     * @param data.maxHabitabilityScore
     * @param data.minHabitabilityConfidence
     * @param data.minDistanceFromEarth
     * @param data.maxDistanceFromEarth
     * @param data.minEquilibriumTemperature
     * @param data.maxEquilibriumTemperature
     * @param data.systemPlanetCount
     * @param data.minSystemPlanetCount
     * @param data.minOrbitalEccentricity
     * @param data.maxOrbitalEccentricity
     * @returns ExoplanetsPublic Successful Response
     * @throws ApiError
     */
    public static readExoplanets(data: ExoplanetsReadExoplanetsData = {}): CancelablePromise<ExoplanetsReadExoplanetsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/exoplanets/',
            query: {
                skip: data.skip,
                limit: data.limit,
                planet_name: data.planetName,
                host_star: data.hostStar,
                discovery_method: data.discoveryMethod,
                discovery_year: data.discoveryYear,
                min_discovery_year: data.minDiscoveryYear,
                max_discovery_year: data.maxDiscoveryYear,
                min_orbital_period: data.minOrbitalPeriod,
                max_orbital_period: data.maxOrbitalPeriod,
                min_planet_radius: data.minPlanetRadius,
                max_planet_radius: data.maxPlanetRadius,
                min_planet_mass: data.minPlanetMass,
                max_planet_mass: data.maxPlanetMass,
                composition: data.composition,
                min_composition_confidence: data.minCompositionConfidence,
                min_habitability_score: data.minHabitabilityScore,
                max_habitability_score: data.maxHabitabilityScore,
                min_habitability_confidence: data.minHabitabilityConfidence,
                min_distance_from_earth: data.minDistanceFromEarth,
                max_distance_from_earth: data.maxDistanceFromEarth,
                min_equilibrium_temperature: data.minEquilibriumTemperature,
                max_equilibrium_temperature: data.maxEquilibriumTemperature,
                system_planet_count: data.systemPlanetCount,
                min_system_planet_count: data.minSystemPlanetCount,
                min_orbital_eccentricity: data.minOrbitalEccentricity,
                max_orbital_eccentricity: data.maxOrbitalEccentricity
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Exoplanet Stats
     * Retrieve statistics about the exoplanets dataset.
     * @param data The data for the request.
     * @param data.habitabilityScoreThreshold
     * @param data.habitabilityConfidenceThreshold
     * @returns ExoplanetStats Successful Response
     * @throws ApiError
     */
    public static getExoplanetStats(data: ExoplanetsGetExoplanetStatsData = {}): CancelablePromise<ExoplanetsGetExoplanetStatsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/exoplanets/stats',
            query: {
                habitability_score_threshold: data.habitabilityScoreThreshold,
                habitability_confidence_threshold: data.habitabilityConfidenceThreshold
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Exoplanet By Id
     * Get a specific exoplanet by ID.
     * @param data The data for the request.
     * @param data.exoplanetId
     * @returns ExoplanetPublic Successful Response
     * @throws ApiError
     */
    public static readExoplanetById(data: ExoplanetsReadExoplanetByIdData): CancelablePromise<ExoplanetsReadExoplanetByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/exoplanets/{exoplanet_id}',
            path: {
                exoplanet_id: data.exoplanetId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * @param data The data for the request.
     * @param data.itemId
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{item_id}',
            path: {
                item_id: data.itemId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * @param data The data for the request.
     * @param data.itemId
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{item_id}',
            path: {
                item_id: data.itemId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * @param data The data for the request.
     * @param data.itemId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{item_id}',
            path: {
                item_id: data.itemId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtml(data: LoginRecoverPasswordHtmlData): CancelablePromise<LoginRecoverPasswordHtmlResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUser(data: UsersReadUserData): CancelablePromise<UsersReadUserResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * @param data The data for the request.
     * @param data.userId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}