// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { MetricsResponse, EtlRunExoplanetEtlData, EtlRunExoplanetEtlResponse, EtlReadLastEtlRunResponse, EtlReadEtlRunsData, EtlReadEtlRunsResponse, ExoplanetsReadExoplanetsData, ExoplanetsReadExoplanetsResponse, ExoplanetsReadExoplanetsFieldsData, ExoplanetsReadExoplanetsFieldsResponse, ExoplanetsGetExoplanetStatsData, ExoplanetsGetExoplanetStatsResponse, ExoplanetsReadExoplanetByIdData, ExoplanetsReadExoplanetByIdResponse, ExportsExportExoplanetsEndpointData, ExportsExportExoplanetsEndpointResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlData, LoginRecoverPasswordHtmlResponse, PrivateCreateUserData, PrivateCreateUserResponse, SchedulerReadSchedulerStatusResponse, SchedulerUpdateSchedulerData, SchedulerUpdateSchedulerResponse, SchedulerStartSchedulerRouteResponse, SchedulerStopSchedulerRouteResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersReadUserData, UsersReadUserResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsPurgeCacheResponse, UtilsHealthCheckResponse } from './types.gen';

export class DefaultService {
    /**
     * Metrics
     * Endpoint that serves Prometheus metrics.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static metrics(): CancelablePromise<MetricsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/metrics'
        });
    }
}

export class EtlService {
    /**
     * Trigger ETL pipeline
     * Trigger the exoplanet ETL ingestion pipeline with customizable limits and loading modes (admin only).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ETLRunResponse Successful Response
     * @throws ApiError
     */
    public static runExoplanetEtl(data: EtlRunExoplanetEtlData): CancelablePromise<EtlRunExoplanetEtlResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/etl/run',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get last ETL run report
     * Retrieve the execution metrics and report of the most recent ETL pipeline run (admin only).
     * @returns ETLLastRunResponse Successful Response
     * @throws ApiError
     */
    public static readLastEtlRun(): CancelablePromise<EtlReadLastEtlRunResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/etl/last_run'
        });
    }
    
    /**
     * List ETL pipeline runs
     * Retrieve paginated historical execution records of past ETL pipeline runs (admin only).
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ETLRunsResponse Successful Response
     * @throws ApiError
     */
    public static readEtlRuns(data: EtlReadEtlRunsData = {}): CancelablePromise<EtlReadEtlRunsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/etl/runs',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ExoplanetsService {
    /**
     * List exoplanets
     * Retrieve a paginated and filterable list of exoplanets with full physical and astrophysical properties.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.sortBy
     * @param data.order
     * @param data.planetName
     * @param data.hostStar
     * @param data.discoveryMethod
     * @param data.discoveryYear
     * @param data.minDiscoveryYear
     * @param data.maxDiscoveryYear
     * @param data.minOrbitalPeriod
     * @param data.maxOrbitalPeriod
     * @param data.minPlanetRadius
     * @param data.maxPlanetRadius
     * @param data.minPlanetMass
     * @param data.maxPlanetMass
     * @param data.planetClass
     * @param data.minPlanetClassConfidence
     * @param data.maxPlanetClassConfidence
     * @param data.composition
     * @param data.minCompositionConfidence
     * @param data.maxCompositionConfidence
     * @param data.minHabitabilityScore
     * @param data.maxHabitabilityScore
     * @param data.minHabitabilityConfidence
     * @param data.maxHabitabilityConfidence
     * @param data.minDistanceFromEarth
     * @param data.maxDistanceFromEarth
     * @param data.minEquilibriumTemperature
     * @param data.maxEquilibriumTemperature
     * @param data.systemPlanetCount
     * @param data.minSystemPlanetCount
     * @param data.minOrbitalEccentricity
     * @param data.maxOrbitalEccentricity
     * @param data.hasNasaPhoto
     * @returns ExoplanetsQueryResponse Successful Response
     * @throws ApiError
     */
    public static readExoplanets(data: ExoplanetsReadExoplanetsData = {}): CancelablePromise<ExoplanetsReadExoplanetsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/exoplanets/',
            query: {
                skip: data.skip,
                limit: data.limit,
                sort_by: data.sortBy,
                order: data.order,
                planet_name: data.planetName,
                host_star: data.hostStar,
                discovery_method: data.discoveryMethod,
                discovery_year: data.discoveryYear,
                min_discovery_year: data.minDiscoveryYear,
                max_discovery_year: data.maxDiscoveryYear,
                min_orbital_period: data.minOrbitalPeriod,
                max_orbital_period: data.maxOrbitalPeriod,
                min_planet_radius: data.minPlanetRadius,
                max_planet_radius: data.maxPlanetRadius,
                min_planet_mass: data.minPlanetMass,
                max_planet_mass: data.maxPlanetMass,
                planet_class: data.planetClass,
                min_planet_class_confidence: data.minPlanetClassConfidence,
                max_planet_class_confidence: data.maxPlanetClassConfidence,
                composition: data.composition,
                min_composition_confidence: data.minCompositionConfidence,
                max_composition_confidence: data.maxCompositionConfidence,
                min_habitability_score: data.minHabitabilityScore,
                max_habitability_score: data.maxHabitabilityScore,
                min_habitability_confidence: data.minHabitabilityConfidence,
                max_habitability_confidence: data.maxHabitabilityConfidence,
                min_distance_from_earth: data.minDistanceFromEarth,
                max_distance_from_earth: data.maxDistanceFromEarth,
                min_equilibrium_temperature: data.minEquilibriumTemperature,
                max_equilibrium_temperature: data.maxEquilibriumTemperature,
                system_planet_count: data.systemPlanetCount,
                min_system_planet_count: data.minSystemPlanetCount,
                min_orbital_eccentricity: data.minOrbitalEccentricity,
                max_orbital_eccentricity: data.maxOrbitalEccentricity,
                has_nasa_photo: data.hasNasaPhoto
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List exoplanets with selected fields
     * Retrieve exoplanets projecting only specified fields to minimize bandwidth and payload size.
     * @param data The data for the request.
     * @param data.fields List of fields to project in response items.
     * @param data.skip
     * @param data.limit
     * @param data.sortBy
     * @param data.order
     * @param data.planetName
     * @param data.hostStar
     * @param data.discoveryMethod
     * @param data.discoveryYear
     * @param data.minDiscoveryYear
     * @param data.maxDiscoveryYear
     * @param data.minOrbitalPeriod
     * @param data.maxOrbitalPeriod
     * @param data.minPlanetRadius
     * @param data.maxPlanetRadius
     * @param data.minPlanetMass
     * @param data.maxPlanetMass
     * @param data.planetClass
     * @param data.minPlanetClassConfidence
     * @param data.maxPlanetClassConfidence
     * @param data.composition
     * @param data.minCompositionConfidence
     * @param data.maxCompositionConfidence
     * @param data.minHabitabilityScore
     * @param data.maxHabitabilityScore
     * @param data.minHabitabilityConfidence
     * @param data.maxHabitabilityConfidence
     * @param data.minDistanceFromEarth
     * @param data.maxDistanceFromEarth
     * @param data.minEquilibriumTemperature
     * @param data.maxEquilibriumTemperature
     * @param data.systemPlanetCount
     * @param data.minSystemPlanetCount
     * @param data.minOrbitalEccentricity
     * @param data.maxOrbitalEccentricity
     * @param data.hasNasaPhoto
     * @returns ExoplanetsQueryResponse Successful Response
     * @throws ApiError
     */
    public static readExoplanetsFields(data: ExoplanetsReadExoplanetsFieldsData): CancelablePromise<ExoplanetsReadExoplanetsFieldsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/exoplanets/fields',
            query: {
                fields: data.fields,
                skip: data.skip,
                limit: data.limit,
                sort_by: data.sortBy,
                order: data.order,
                planet_name: data.planetName,
                host_star: data.hostStar,
                discovery_method: data.discoveryMethod,
                discovery_year: data.discoveryYear,
                min_discovery_year: data.minDiscoveryYear,
                max_discovery_year: data.maxDiscoveryYear,
                min_orbital_period: data.minOrbitalPeriod,
                max_orbital_period: data.maxOrbitalPeriod,
                min_planet_radius: data.minPlanetRadius,
                max_planet_radius: data.maxPlanetRadius,
                min_planet_mass: data.minPlanetMass,
                max_planet_mass: data.maxPlanetMass,
                planet_class: data.planetClass,
                min_planet_class_confidence: data.minPlanetClassConfidence,
                max_planet_class_confidence: data.maxPlanetClassConfidence,
                composition: data.composition,
                min_composition_confidence: data.minCompositionConfidence,
                max_composition_confidence: data.maxCompositionConfidence,
                min_habitability_score: data.minHabitabilityScore,
                max_habitability_score: data.maxHabitabilityScore,
                min_habitability_confidence: data.minHabitabilityConfidence,
                max_habitability_confidence: data.maxHabitabilityConfidence,
                min_distance_from_earth: data.minDistanceFromEarth,
                max_distance_from_earth: data.maxDistanceFromEarth,
                min_equilibrium_temperature: data.minEquilibriumTemperature,
                max_equilibrium_temperature: data.maxEquilibriumTemperature,
                system_planet_count: data.systemPlanetCount,
                min_system_planet_count: data.minSystemPlanetCount,
                min_orbital_eccentricity: data.minOrbitalEccentricity,
                max_orbital_eccentricity: data.maxOrbitalEccentricity,
                has_nasa_photo: data.hasNasaPhoto
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get exoplanet statistics
     * Retrieve aggregated analytics and summary distributions for the exoplanets catalogue.
     * @param data The data for the request.
     * @param data.habitabilityScoreThreshold Minimum habitability score threshold (0-100 scale).
     * @param data.habitabilityConfidenceThreshold Minimum habitability confidence threshold (0.0-1.0 scale).
     * @returns ExoplanetStats Successful Response
     * @throws ApiError
     */
    public static getExoplanetStats(data: ExoplanetsGetExoplanetStatsData = {}): CancelablePromise<ExoplanetsGetExoplanetStatsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/exoplanets/stats',
            query: {
                habitability_score_threshold: data.habitabilityScoreThreshold,
                habitability_confidence_threshold: data.habitabilityConfidenceThreshold
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get exoplanet by ID
     * Retrieve complete astrophysical record and verified imagery for a single exoplanet by UUID.
     * @param data The data for the request.
     * @param data.exoplanetId
     * @returns ExoplanetPublic Successful Response
     * @throws ApiError
     */
    public static readExoplanetById(data: ExoplanetsReadExoplanetByIdData): CancelablePromise<ExoplanetsReadExoplanetByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/exoplanets/{exoplanet_id}',
            path: {
                exoplanet_id: data.exoplanetId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ExportsService {
    /**
     * Export exoplanets dataset
     * Export filtered exoplanet data to a downloadable file stream in CSV, JSON, or Parquet format.
     * @param data The data for the request.
     * @param data.format
     * @param data.filename Base name for the generated download file.
     * @param data.fields List of fields to include in export (omit to export all fields).
     * @param data.compress Whether to compress the exported file into a ZIP archive.
     * @param data.planetName
     * @param data.hostStar
     * @param data.discoveryMethod
     * @param data.discoveryYear
     * @param data.minDiscoveryYear
     * @param data.maxDiscoveryYear
     * @param data.minOrbitalPeriod
     * @param data.maxOrbitalPeriod
     * @param data.minPlanetRadius
     * @param data.maxPlanetRadius
     * @param data.minPlanetMass
     * @param data.maxPlanetMass
     * @param data.planetClass
     * @param data.minPlanetClassConfidence
     * @param data.maxPlanetClassConfidence
     * @param data.composition
     * @param data.minCompositionConfidence
     * @param data.maxCompositionConfidence
     * @param data.minHabitabilityScore
     * @param data.maxHabitabilityScore
     * @param data.minHabitabilityConfidence
     * @param data.maxHabitabilityConfidence
     * @param data.minDistanceFromEarth
     * @param data.maxDistanceFromEarth
     * @param data.minEquilibriumTemperature
     * @param data.maxEquilibriumTemperature
     * @param data.systemPlanetCount
     * @param data.minSystemPlanetCount
     * @param data.minOrbitalEccentricity
     * @param data.maxOrbitalEccentricity
     * @param data.hasNasaPhoto
     * @param data.sortBy
     * @param data.order
     * @returns unknown Exported data file as attachment stream.
     * @throws ApiError
     */
    public static exportExoplanetsEndpoint(data: ExportsExportExoplanetsEndpointData = {}): CancelablePromise<ExportsExportExoplanetsEndpointResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/exports/export',
            query: {
                format: data.format,
                filename: data.filename,
                fields: data.fields,
                compress: data.compress,
                planet_name: data.planetName,
                host_star: data.hostStar,
                discovery_method: data.discoveryMethod,
                discovery_year: data.discoveryYear,
                min_discovery_year: data.minDiscoveryYear,
                max_discovery_year: data.maxDiscoveryYear,
                min_orbital_period: data.minOrbitalPeriod,
                max_orbital_period: data.maxOrbitalPeriod,
                min_planet_radius: data.minPlanetRadius,
                max_planet_radius: data.maxPlanetRadius,
                min_planet_mass: data.minPlanetMass,
                max_planet_mass: data.maxPlanetMass,
                planet_class: data.planetClass,
                min_planet_class_confidence: data.minPlanetClassConfidence,
                max_planet_class_confidence: data.maxPlanetClassConfidence,
                composition: data.composition,
                min_composition_confidence: data.minCompositionConfidence,
                max_composition_confidence: data.maxCompositionConfidence,
                min_habitability_score: data.minHabitabilityScore,
                max_habitability_score: data.maxHabitabilityScore,
                min_habitability_confidence: data.minHabitabilityConfidence,
                max_habitability_confidence: data.maxHabitabilityConfidence,
                min_distance_from_earth: data.minDistanceFromEarth,
                max_distance_from_earth: data.maxDistanceFromEarth,
                min_equilibrium_temperature: data.minEquilibriumTemperature,
                max_equilibrium_temperature: data.maxEquilibriumTemperature,
                system_planet_count: data.systemPlanetCount,
                min_system_planet_count: data.minSystemPlanetCount,
                min_orbital_eccentricity: data.minOrbitalEccentricity,
                max_orbital_eccentricity: data.maxOrbitalEccentricity,
                has_nasa_photo: data.hasNasaPhoto,
                sort_by: data.sortBy,
                order: data.order
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * OAuth2 login for access token
     * Authenticate user via OAuth2 password credentials and return an access token.
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test access token
     * Verify validity of the current access token and return user profile.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover password
     * Send a password recovery email if the email is registered in the system.
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset password
     * Reset user password using a verified recovery token.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Preview password recovery email
     * Generate and preview the HTML content of the password recovery email (admin debug).
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtml(data: LoginRecoverPasswordHtmlData): CancelablePromise<LoginRecoverPasswordHtmlResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create user (local dev)
     * Create a user directly in the database without requiring authentication (local development only).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SchedulerService {
    /**
     * Get scheduler status
     * Retrieve the current status of the background ETL scheduler (admin only).
     * @returns SchedulerStatusResponse Successful Response
     * @throws ApiError
     */
    public static readSchedulerStatus(): CancelablePromise<SchedulerReadSchedulerStatusResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/scheduler/'
        });
    }
    
    /**
     * Update scheduler interval
     * Update the execution frequency of the background ETL scheduler (admin only).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SchedulerStatusResponse Successful Response
     * @throws ApiError
     */
    public static updateScheduler(data: SchedulerUpdateSchedulerData): CancelablePromise<SchedulerUpdateSchedulerResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/scheduler/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Start scheduler
     * Start the background ETL scheduler (admin only).
     * @returns SchedulerStatusResponse Successful Response
     * @throws ApiError
     */
    public static startSchedulerRoute(): CancelablePromise<SchedulerStartSchedulerRouteResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/scheduler/start'
        });
    }
    
    /**
     * Stop scheduler
     * Stop the background ETL scheduler (admin only).
     * @returns SchedulerStatusResponse Successful Response
     * @throws ApiError
     */
    public static stopSchedulerRoute(): CancelablePromise<SchedulerStopSchedulerRouteResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/scheduler/stop'
        });
    }
}

export class UsersService {
    /**
     * List users
     * Retrieve a paginated list of registered users (admin only).
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create user
     * Create a new administrator user (admin only).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get current user
     * Retrieve profile information for the authenticated user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update current user
     * Update profile details for the authenticated user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update current user password
     * Change password for the authenticated user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get user by ID
     * Retrieve user details by unique identifier (admin only).
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUser(data: UsersReadUserData): CancelablePromise<UsersReadUserResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update user by ID
     * Update user information by unique identifier (admin only).
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete user by ID
     * Delete a user account by unique identifier (admin only).
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Send test email
     * Send a test email to verify SMTP delivery and template rendering (admin only).
     * @param data The data for the request.
     * @param data.emailTo Recipient email address for the test message.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Purge application cache
     * Invalidate and clear both Redis and local in-memory caches (admin only).
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static purgeCache(): CancelablePromise<UtilsPurgeCacheResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/purge-cache/'
        });
    }
    
    /**
     * System health check
     * Service liveness probe confirming the API application is healthy and responsive.
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}