// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CompletenessStats = {
    host_star: number;
    discovery_year: number;
    discovery_method: number;
    planet_radius: number;
    planet_mass: number;
    planet_density: number;
    equilibrium_temperature: number;
    incident_flux: number;
    orbital_period: number;
    semi_major_axis: number;
    orbital_eccentricity: number;
    stellar_effective_temperature: number;
    stellar_radius: number;
    stellar_mass: number;
    stellar_luminosity: number;
    stellar_age: number;
    distance_from_earth: number;
    system_planet_count: number;
    system_star_count: number;
    composition: number;
    composition_confidence: number;
    habitability_score: number;
    habitability_confidence: number;
};

export type CompositionStats = {
    by_composition: {
        [key: string]: (number);
    };
    average_confidence?: (number | null);
};

export type ETLConfig = {
    /**
     * Max number of records to extract. None = no limit
     */
    limit?: (number | null);
    dry_run?: boolean;
    persist_run?: boolean;
    load_mode?: LoadMode;
};

export type ExoplanetPublic = {
    planet_name: string;
    host_star?: (string | null);
    discovery_year?: (number | null);
    discovery_method?: (string | null);
    planet_radius?: (number | null);
    planet_mass?: (number | null);
    planet_density?: (number | null);
    equilibrium_temperature?: (number | null);
    incident_flux?: (number | null);
    orbital_period?: (number | null);
    semi_major_axis?: (number | null);
    orbital_eccentricity?: (number | null);
    stellar_effective_temperature?: (number | null);
    stellar_radius?: (number | null);
    stellar_mass?: (number | null);
    stellar_luminosity?: (number | null);
    stellar_age?: (number | null);
    distance_from_earth?: (number | null);
    system_planet_count?: (number | null);
    system_star_count?: (number | null);
    composition?: (PlanetComposition | null);
    composition_confidence?: (number | null);
    habitability_score?: (number | null);
    habitability_confidence?: (number | null);
    id: string;
};

export type ExoplanetsPublic = {
    data: Array<ExoplanetPublic>;
    count: number;
};

export type ExoplanetStats = {
    total: number;
    by_method: {
        [key: string]: (number);
    };
    by_decade: {
        [key: string]: (number);
    };
    composition: CompositionStats;
    habitability: HabitabilityStats;
    radius: SummaryStats;
    mass: SummaryStats;
    density: SummaryStats;
    equilibrium_temperature: SummaryStats;
    orbital_period: SummaryStats;
    distance: SummaryStats;
    completeness: CompletenessStats;
};

export type ExportFormat = 'csv' | 'json' | 'parquet';

export type HabitabilityStats = {
    average?: (number | null);
    minimum?: (number | null);
    maximum?: (number | null);
    average_confidence?: (number | null);
    potentially_habitable?: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type LoadMode = 'upsert' | 'insert' | 'reload';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PlanetComposition = 'Rocky' | 'Super Earth' | 'Mini Neptune' | 'Ice Giant' | 'Gas Giant' | 'Unknown';

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SummaryStats = {
    average?: (number | null);
    minimum?: (number | null);
    maximum?: (number | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type MetricsResponse = (unknown);

export type EtlRunExoplanetEtlData = {
    requestBody: ETLConfig;
};

export type EtlRunExoplanetEtlResponse = (unknown);

export type ExoplanetsReadExoplanetsData = {
    composition?: (PlanetComposition | null);
    discoveryMethod?: (string | null);
    discoveryYear?: (number | null);
    hostStar?: (string | null);
    limit?: number;
    maxDiscoveryYear?: (number | null);
    maxDistanceFromEarth?: (number | null);
    maxEquilibriumTemperature?: (number | null);
    maxHabitabilityScore?: (number | null);
    maxOrbitalEccentricity?: (number | null);
    maxOrbitalPeriod?: (number | null);
    maxPlanetMass?: (number | null);
    maxPlanetRadius?: (number | null);
    minCompositionConfidence?: (number | null);
    minDiscoveryYear?: (number | null);
    minDistanceFromEarth?: (number | null);
    minEquilibriumTemperature?: (number | null);
    minHabitabilityConfidence?: (number | null);
    minHabitabilityScore?: (number | null);
    minOrbitalEccentricity?: (number | null);
    minOrbitalPeriod?: (number | null);
    minPlanetMass?: (number | null);
    minPlanetRadius?: (number | null);
    minSystemPlanetCount?: (number | null);
    planetName?: (string | null);
    skip?: number;
    systemPlanetCount?: (number | null);
};

export type ExoplanetsReadExoplanetsResponse = (ExoplanetsPublic);

export type ExoplanetsGetExoplanetStatsData = {
    habitabilityConfidenceThreshold?: number;
    habitabilityScoreThreshold?: number;
};

export type ExoplanetsGetExoplanetStatsResponse = (ExoplanetStats);

export type ExoplanetsReadExoplanetByIdData = {
    exoplanetId: string;
};

export type ExoplanetsReadExoplanetByIdResponse = (ExoplanetPublic);

export type ExportsExportExoplanetsEndpointData = {
    composition?: (PlanetComposition | null);
    compress?: boolean;
    discoveryMethod?: (string | null);
    discoveryYear?: (number | null);
    fields?: (Array<(string)> | null);
    filename?: string;
    format?: ExportFormat;
    hostStar?: (string | null);
    maxDiscoveryYear?: (number | null);
    maxDistanceFromEarth?: (number | null);
    maxEquilibriumTemperature?: (number | null);
    maxHabitabilityScore?: (number | null);
    maxOrbitalEccentricity?: (number | null);
    maxOrbitalPeriod?: (number | null);
    maxPlanetMass?: (number | null);
    maxPlanetRadius?: (number | null);
    minCompositionConfidence?: (number | null);
    minDiscoveryYear?: (number | null);
    minDistanceFromEarth?: (number | null);
    minEquilibriumTemperature?: (number | null);
    minHabitabilityConfidence?: (number | null);
    minHabitabilityScore?: (number | null);
    minOrbitalEccentricity?: (number | null);
    minOrbitalPeriod?: (number | null);
    minPlanetMass?: (number | null);
    minPlanetRadius?: (number | null);
    minSystemPlanetCount?: (number | null);
    planetName?: (string | null);
    systemPlanetCount?: (number | null);
};

export type ExportsExportExoplanetsEndpointResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    itemId: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    itemId: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    itemId: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlData = {
    email: string;
};

export type LoginRecoverPasswordHtmlResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserData = {
    userId: string;
};

export type UsersReadUserResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (unknown);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);