// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CompletenessStats = {
    host_star: number;
    discovery_year: number;
    discovery_method: number;
    planet_radius: number;
    planet_mass: number;
    planet_density: number;
    equilibrium_temperature: number;
    incident_flux: number;
    orbital_period: number;
    semi_major_axis: number;
    orbital_eccentricity: number;
    stellar_effective_temperature: number;
    stellar_radius: number;
    stellar_mass: number;
    stellar_luminosity: number;
    stellar_age: number;
    distance_from_earth: number;
    system_planet_count: number;
    system_star_count: number;
    planet_class: number;
    planet_class_confidence: number;
    composition: number;
    composition_confidence: number;
    habitability_score: number;
    habitability_confidence: number;
};

export type CompositionStats = {
    by_composition: {
        [key: string]: (number);
    };
    average_confidence?: (number | null);
};

export type ETLConfig = {
    /**
     * Maximum number of records to extract from NASA TAP service (None = full extraction).
     */
    limit?: (number | null);
    /**
     * If True, runs extraction and transformation without persisting to database.
     */
    dry_run?: boolean;
    /**
     * Whether to save the execution metrics and summary in the database.
     */
    persist_run?: boolean;
    /**
     * Database load strategy: upsert, insert, or reload.
     */
    load_mode?: LoadMode;
};

export type ETLLastRunResponse = {
    status?: string;
    report?: (ETLRunItem | null);
};

export type ETLReport = {
    extracted?: number;
    transformed?: number;
    load_result?: LoadResult;
    started_at?: (string | null);
    finished_at?: (string | null);
    success?: boolean;
    errors?: Array<(string)>;
    duration_seconds?: number;
    extract_time?: number;
    transform_time?: number;
    load_time?: number;
};

export type ETLRunItem = {
    id: string;
    started_at: string;
    finished_at?: (string | null);
    extracted?: number;
    transformed?: number;
    load_result?: {
        [key: string]: unknown;
    };
    extract_time?: number;
    transform_time?: number;
    load_time?: number;
    total_time?: number;
    success?: boolean;
    errors?: string;
};

export type ETLRunResponse = {
    status?: string;
    report: ETLReport;
};

export type ETLRunsResponse = {
    status?: string;
    count: number;
    runs: Array<ETLRunItem>;
};

export type ExoplanetField = 'planet_name' | 'host_star' | 'discovery_year' | 'discovery_method' | 'planet_radius' | 'planet_mass' | 'planet_density' | 'equilibrium_temperature' | 'incident_flux' | 'orbital_period' | 'semi_major_axis' | 'orbital_eccentricity' | 'stellar_effective_temperature' | 'stellar_radius' | 'stellar_mass' | 'stellar_luminosity' | 'stellar_age' | 'distance_from_earth' | 'system_planet_count' | 'system_star_count' | 'planet_class' | 'planet_class_confidence' | 'composition' | 'composition_confidence' | 'habitability_score' | 'habitability_confidence' | 'photo_url';

export type ExoplanetFilters = {
    planet_name?: (string | null);
    host_star?: (string | null);
    discovery_method?: (string | null);
    discovery_year?: (number | null);
    min_discovery_year?: (number | null);
    max_discovery_year?: (number | null);
    /**
     * Minimum orbital period in days.
     */
    min_orbital_period?: (number | null);
    /**
     * Maximum orbital period in days.
     */
    max_orbital_period?: (number | null);
    /**
     * Minimum planet radius in Earth radii (R⊕).
     */
    min_planet_radius?: (number | null);
    /**
     * Maximum planet radius in Earth radii (R⊕).
     */
    max_planet_radius?: (number | null);
    /**
     * Minimum planet mass in Earth masses (M⊕).
     */
    min_planet_mass?: (number | null);
    /**
     * Maximum planet mass in Earth masses (M⊕).
     */
    max_planet_mass?: (number | null);
    planet_class?: (PlanetClass | null);
    min_planet_class_confidence?: (number | null);
    max_planet_class_confidence?: (number | null);
    composition?: (PlanetComposition | null);
    min_composition_confidence?: (number | null);
    max_composition_confidence?: (number | null);
    /**
     * Minimum habitability score (0-100 scale).
     */
    min_habitability_score?: (number | null);
    /**
     * Maximum habitability score (0-100 scale).
     */
    max_habitability_score?: (number | null);
    min_habitability_confidence?: (number | null);
    max_habitability_confidence?: (number | null);
    /**
     * Minimum distance from Earth in parsecs (pc).
     */
    min_distance_from_earth?: (number | null);
    /**
     * Maximum distance from Earth in parsecs (pc).
     */
    max_distance_from_earth?: (number | null);
    /**
     * Minimum planetary equilibrium temperature in Kelvin (K).
     */
    min_equilibrium_temperature?: (number | null);
    /**
     * Maximum planetary equilibrium temperature in Kelvin (K).
     */
    max_equilibrium_temperature?: (number | null);
    system_planet_count?: (number | null);
    min_system_planet_count?: (number | null);
    min_orbital_eccentricity?: (number | null);
    max_orbital_eccentricity?: (number | null);
    /**
     * Filter planets having verified NASA imagery.
     */
    has_nasa_photo?: (boolean | null);
    sort_by?: (ExoplanetSortField | null);
    order?: SortOrder;
};

export type ExoplanetPublic = {
    planet_name: string;
    host_star?: (string | null);
    discovery_year?: (number | null);
    discovery_method?: (string | null);
    planet_radius?: (number | null);
    planet_mass?: (number | null);
    planet_density?: (number | null);
    equilibrium_temperature?: (number | null);
    incident_flux?: (number | null);
    orbital_period?: (number | null);
    semi_major_axis?: (number | null);
    orbital_eccentricity?: (number | null);
    stellar_effective_temperature?: (number | null);
    stellar_radius?: (number | null);
    stellar_mass?: (number | null);
    stellar_luminosity?: (number | null);
    stellar_age?: (number | null);
    distance_from_earth?: (number | null);
    system_planet_count?: (number | null);
    system_star_count?: (number | null);
    planet_class?: (PlanetClass | null);
    planet_class_confidence?: (number | null);
    composition?: (PlanetComposition | null);
    composition_confidence?: (number | null);
    habitability_score?: (number | null);
    habitability_confidence?: (number | null);
    photo_url?: (string | null);
    id: string;
};

export type ExoplanetQueryMetadata = {
    count: number;
    returned: number;
    skip: number;
    limit: number;
    sort_by: ExoplanetSortField;
    order: SortOrder;
    fields?: (Array<ExoplanetField> | null);
    filters: ExoplanetFilters;
};

export type ExoplanetSortField = 'planet_name' | 'host_star' | 'discovery_year' | 'discovery_method' | 'planet_radius' | 'planet_mass' | 'planet_density' | 'equilibrium_temperature' | 'incident_flux' | 'orbital_period' | 'semi_major_axis' | 'orbital_eccentricity' | 'stellar_effective_temperature' | 'stellar_radius' | 'stellar_mass' | 'stellar_luminosity' | 'stellar_age' | 'distance_from_earth' | 'system_planet_count' | 'system_star_count' | 'planet_class' | 'planet_class_confidence' | 'composition' | 'composition_confidence' | 'habitability_score' | 'habitability_confidence';

export type ExoplanetsQueryResponse = {
    data: Array<unknown>;
    meta: ExoplanetQueryMetadata;
};

export type ExoplanetStats = {
    total: number;
    by_method: {
        [key: string]: (number);
    };
    by_decade: {
        [key: string]: (number);
    };
    planet_class: PlanetClassStats;
    composition: CompositionStats;
    habitability: HabitabilityStats;
    radius: SummaryStats;
    mass: SummaryStats;
    density: SummaryStats;
    equilibrium_temperature: SummaryStats;
    orbital_period: SummaryStats;
    distance: SummaryStats;
    completeness: CompletenessStats;
};

export type ExportFormat = 'csv' | 'json' | 'parquet';

export type HabitabilityStats = {
    average?: (number | null);
    minimum?: (number | null);
    maximum?: (number | null);
    average_confidence?: (number | null);
    potentially_habitable?: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LoadMode = 'upsert' | 'insert' | 'reload';

export type LoadResult = {
    attempted?: number;
    inserted?: number;
    updated?: number;
    skipped?: number;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PlanetClass = 'Terrestrial' | 'Super Earth' | 'Sub-Neptune' | 'Neptune' | 'Ice Giant' | 'Gas Giant' | 'Unknown';

export type PlanetClassStats = {
    by_class: {
        [key: string]: (number);
    };
    average_confidence?: (number | null);
};

export type PlanetComposition = 'Rocky' | 'Rocky-Iron' | 'Water World' | 'Ice' | 'Hydrogen-Helium' | 'Unknown';

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SchedulerStatus = {
    running: boolean;
    interval_seconds?: (number | null);
    next_run?: (string | null);
    next_run_time?: (string | null);
};

export type SchedulerStatusResponse = {
    status?: string;
    scheduler: SchedulerStatus;
};

export type SchedulerUpdate = {
    /**
     * Execution interval in seconds for the background ETL job (minimum 60s).
     */
    interval_seconds: number;
};

export type SortOrder = 'asc' | 'desc';

export type SummaryStats = {
    average?: (number | null);
    minimum?: (number | null);
    maximum?: (number | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type MetricsResponse = (unknown);

export type EtlRunExoplanetEtlData = {
    requestBody: ETLConfig;
};

export type EtlRunExoplanetEtlResponse = (ETLRunResponse);

export type EtlReadLastEtlRunResponse = (ETLLastRunResponse);

export type EtlReadEtlRunsData = {
    limit?: number;
    skip?: number;
};

export type EtlReadEtlRunsResponse = (ETLRunsResponse);

export type ExoplanetsReadExoplanetsData = {
    composition?: (PlanetComposition | null);
    discoveryMethod?: (string | null);
    discoveryYear?: (number | null);
    hasNasaPhoto?: (boolean | null);
    hostStar?: (string | null);
    limit?: number;
    maxCompositionConfidence?: (number | null);
    maxDiscoveryYear?: (number | null);
    maxDistanceFromEarth?: (number | null);
    maxEquilibriumTemperature?: (number | null);
    maxHabitabilityConfidence?: (number | null);
    maxHabitabilityScore?: (number | null);
    maxOrbitalEccentricity?: (number | null);
    maxOrbitalPeriod?: (number | null);
    maxPlanetClassConfidence?: (number | null);
    maxPlanetMass?: (number | null);
    maxPlanetRadius?: (number | null);
    minCompositionConfidence?: (number | null);
    minDiscoveryYear?: (number | null);
    minDistanceFromEarth?: (number | null);
    minEquilibriumTemperature?: (number | null);
    minHabitabilityConfidence?: (number | null);
    minHabitabilityScore?: (number | null);
    minOrbitalEccentricity?: (number | null);
    minOrbitalPeriod?: (number | null);
    minPlanetClassConfidence?: (number | null);
    minPlanetMass?: (number | null);
    minPlanetRadius?: (number | null);
    minSystemPlanetCount?: (number | null);
    order?: SortOrder;
    planetClass?: (PlanetClass | null);
    planetName?: (string | null);
    skip?: number;
    sortBy?: (ExoplanetSortField | null);
    systemPlanetCount?: (number | null);
};

export type ExoplanetsReadExoplanetsResponse = (ExoplanetsQueryResponse);

export type ExoplanetsReadExoplanetsFieldsData = {
    composition?: (PlanetComposition | null);
    discoveryMethod?: (string | null);
    discoveryYear?: (number | null);
    /**
     * List of fields to project in response items.
     */
    fields: Array<ExoplanetField>;
    hasNasaPhoto?: (boolean | null);
    hostStar?: (string | null);
    limit?: number;
    maxCompositionConfidence?: (number | null);
    maxDiscoveryYear?: (number | null);
    maxDistanceFromEarth?: (number | null);
    maxEquilibriumTemperature?: (number | null);
    maxHabitabilityConfidence?: (number | null);
    maxHabitabilityScore?: (number | null);
    maxOrbitalEccentricity?: (number | null);
    maxOrbitalPeriod?: (number | null);
    maxPlanetClassConfidence?: (number | null);
    maxPlanetMass?: (number | null);
    maxPlanetRadius?: (number | null);
    minCompositionConfidence?: (number | null);
    minDiscoveryYear?: (number | null);
    minDistanceFromEarth?: (number | null);
    minEquilibriumTemperature?: (number | null);
    minHabitabilityConfidence?: (number | null);
    minHabitabilityScore?: (number | null);
    minOrbitalEccentricity?: (number | null);
    minOrbitalPeriod?: (number | null);
    minPlanetClassConfidence?: (number | null);
    minPlanetMass?: (number | null);
    minPlanetRadius?: (number | null);
    minSystemPlanetCount?: (number | null);
    order?: SortOrder;
    planetClass?: (PlanetClass | null);
    planetName?: (string | null);
    skip?: number;
    sortBy?: (ExoplanetSortField | null);
    systemPlanetCount?: (number | null);
};

export type ExoplanetsReadExoplanetsFieldsResponse = (ExoplanetsQueryResponse);

export type ExoplanetsGetExoplanetStatsData = {
    /**
     * Minimum habitability confidence threshold (0.0-1.0 scale).
     */
    habitabilityConfidenceThreshold?: number;
    /**
     * Minimum habitability score threshold (0-100 scale).
     */
    habitabilityScoreThreshold?: number;
};

export type ExoplanetsGetExoplanetStatsResponse = (ExoplanetStats);

export type ExoplanetsReadExoplanetByIdData = {
    exoplanetId: string;
};

export type ExoplanetsReadExoplanetByIdResponse = (ExoplanetPublic);

export type ExportsExportExoplanetsEndpointData = {
    composition?: (PlanetComposition | null);
    /**
     * Whether to compress the exported file into a ZIP archive.
     */
    compress?: boolean;
    discoveryMethod?: (string | null);
    discoveryYear?: (number | null);
    /**
     * List of fields to include in export (omit to export all fields).
     */
    fields?: (Array<(string)> | null);
    /**
     * Base name for the generated download file.
     */
    filename?: string;
    format?: ExportFormat;
    hasNasaPhoto?: (boolean | null);
    hostStar?: (string | null);
    maxCompositionConfidence?: (number | null);
    maxDiscoveryYear?: (number | null);
    maxDistanceFromEarth?: (number | null);
    maxEquilibriumTemperature?: (number | null);
    maxHabitabilityConfidence?: (number | null);
    maxHabitabilityScore?: (number | null);
    maxOrbitalEccentricity?: (number | null);
    maxOrbitalPeriod?: (number | null);
    maxPlanetClassConfidence?: (number | null);
    maxPlanetMass?: (number | null);
    maxPlanetRadius?: (number | null);
    minCompositionConfidence?: (number | null);
    minDiscoveryYear?: (number | null);
    minDistanceFromEarth?: (number | null);
    minEquilibriumTemperature?: (number | null);
    minHabitabilityConfidence?: (number | null);
    minHabitabilityScore?: (number | null);
    minOrbitalEccentricity?: (number | null);
    minOrbitalPeriod?: (number | null);
    minPlanetClassConfidence?: (number | null);
    minPlanetMass?: (number | null);
    minPlanetRadius?: (number | null);
    minSystemPlanetCount?: (number | null);
    order?: SortOrder;
    planetClass?: (PlanetClass | null);
    planetName?: (string | null);
    sortBy?: (ExoplanetSortField | null);
    systemPlanetCount?: (number | null);
};

export type ExportsExportExoplanetsEndpointResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlData = {
    email: string;
};

export type LoginRecoverPasswordHtmlResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SchedulerReadSchedulerStatusResponse = (SchedulerStatusResponse);

export type SchedulerUpdateSchedulerData = {
    requestBody: SchedulerUpdate;
};

export type SchedulerUpdateSchedulerResponse = (SchedulerStatusResponse);

export type SchedulerStartSchedulerRouteResponse = (SchedulerStatusResponse);

export type SchedulerStopSchedulerRouteResponse = (SchedulerStatusResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserData = {
    userId: string;
};

export type UsersReadUserResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    /**
     * Recipient email address for the test message.
     */
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsPurgeCacheResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);