"""create etl reports table

Revision ID: 0423268becb0
Revises: 5c8b8caff016
Create Date: 2026-06-28 09:17:59.763501

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0423268becb0'
down_revision = '5c8b8caff016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etlrun',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('extracted', sa.Integer(), nullable=False),
    sa.Column('transformed', sa.Integer(), nullable=False),
    sa.Column('loaded', sa.Integer(), nullable=False),
    sa.Column('extract_time', sa.Float(), nullable=False),
    sa.Column('transform_time', sa.Float(), nullable=False),
    sa.Column('load_time', sa.Float(), nullable=False),
    sa.Column('total_time', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('errors', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etlrun')
    # ### end Alembic commands ###
