"""update ETLRun table LoadResult

Revision ID: 10b16974220e
Revises: 44771f404f35
Create Date: 2026-07-02 08:41:34.315646

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10b16974220e'
down_revision = '44771f404f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etlrun', sa.Column('load_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('etlrun', 'loaded_attempted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etlrun', sa.Column('loaded_attempted', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('etlrun', 'load_result')
    # ### end Alembic commands ###
