"""empty message

Revision ID: 379bafcf16ce
Revises: e97b3c7878f2
Create Date: 2026-07-09 09:03:17.491759

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '379bafcf16ce'
down_revision = 'e97b3c7878f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
