"""update field etlrun

Revision ID: 44771f404f35
Revises: 0423268becb0
Create Date: 2026-06-30 10:12:08.818525

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '44771f404f35'
down_revision = '0423268becb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etlrun', sa.Column('loaded_attempted', sa.Integer(), nullable=False))
    op.drop_column('etlrun', 'loaded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etlrun', sa.Column('loaded', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('etlrun', 'loaded_attempted')
    # ### end Alembic commands ###
