"""add equilibrium temperature field to exoplanet model

Revision ID: 48f38796357e
Revises: 10b16974220e
Create Date: 2026-07-06 09:57:27.132777

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '48f38796357e'
down_revision = '10b16974220e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exoplanet', sa.Column('equilibrium_temperature', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exoplanet', 'equilibrium_temperature')
    # ### end Alembic commands ###
