"""empty message

Revision ID: 5d779f7683ca
Revises: a1b2c3d4e5f6
Create Date: 2026-07-23 10:33:03.757332

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5d779f7683ca'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exoplanet', sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exoplanet', 'photo_url')
    # ### end Alembic commands ###
