"""update exoplanets new fields

Revision ID: 5d9ce81da7a4
Revises: 48f38796357e
Create Date: 2026-07-06 10:33:06.916440

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5d9ce81da7a4'
down_revision = '48f38796357e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exoplanet', sa.Column('planet_density', sa.Float(), nullable=True))
    op.add_column('exoplanet', sa.Column('incident_flux', sa.Float(), nullable=True))
    op.add_column('exoplanet', sa.Column('semi_major_axis', sa.Float(), nullable=True))
    op.add_column('exoplanet', sa.Column('orbital_eccentricity', sa.Float(), nullable=True))
    op.add_column('exoplanet', sa.Column('stellar_effective_temperature', sa.Float(), nullable=True))
    op.add_column('exoplanet', sa.Column('stellar_radius', sa.Float(), nullable=True))
    op.add_column('exoplanet', sa.Column('stellar_mass', sa.Float(), nullable=True))
    op.add_column('exoplanet', sa.Column('stellar_luminosity', sa.Float(), nullable=True))
    op.add_column('exoplanet', sa.Column('stellar_age', sa.Float(), nullable=True))
    op.add_column('exoplanet', sa.Column('distance_from_earth', sa.Float(), nullable=True))
    op.add_column('exoplanet', sa.Column('system_planet_count', sa.Integer(), nullable=True))
    op.add_column('exoplanet', sa.Column('system_star_count', sa.Integer(), nullable=True))
    op.drop_column('exoplanet', 'distance_parsecs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exoplanet', sa.Column('distance_parsecs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('exoplanet', 'system_star_count')
    op.drop_column('exoplanet', 'system_planet_count')
    op.drop_column('exoplanet', 'distance_from_earth')
    op.drop_column('exoplanet', 'stellar_age')
    op.drop_column('exoplanet', 'stellar_luminosity')
    op.drop_column('exoplanet', 'stellar_mass')
    op.drop_column('exoplanet', 'stellar_radius')
    op.drop_column('exoplanet', 'stellar_effective_temperature')
    op.drop_column('exoplanet', 'orbital_eccentricity')
    op.drop_column('exoplanet', 'semi_major_axis')
    op.drop_column('exoplanet', 'incident_flux')
    op.drop_column('exoplanet', 'planet_density')
    # ### end Alembic commands ###
