"""add composition and habitabilty fields

Revision ID: 6a4c71546fdc
Revises: 5d9ce81da7a4
Create Date: 2026-07-07 09:18:57.173695

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6a4c71546fdc'
down_revision = '5d9ce81da7a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exoplanet', sa.Column('habitability_score', sa.Float(), nullable=True))
    op.add_column('exoplanet', sa.Column('composition', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exoplanet', 'composition')
    op.drop_column('exoplanet', 'habitability_score')
    # ### end Alembic commands ###
