"""create exoplanet table

Revision ID: 858f2045fb17
Revises: fe56fa70289e
Create Date: 2026-06-22 09:18:49.678613

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '858f2045fb17'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exoplanet',
    sa.Column('planet_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('host_star', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discovery_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discovery_year', sa.Integer(), nullable=True),
    sa.Column('orbital_period', sa.Float(), nullable=True),
    sa.Column('planet_radius', sa.Float(), nullable=True),
    sa.Column('planet_mass', sa.Float(), nullable=True),
    sa.Column('distance_parsecs', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exoplanet')
    # ### end Alembic commands ###
