"""update fields

Revision ID: b9314ab2b82f
Revises: 6a4c71546fdc
Create Date: 2026-07-07 09:35:57.811115

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b9314ab2b82f'
down_revision = '6a4c71546fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exoplanet', sa.Column('composition_confidence', sa.Float(), nullable=True))
    op.add_column('exoplanet', sa.Column('habitability_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exoplanet', 'habitability_confidence')
    op.drop_column('exoplanet', 'composition_confidence')
    # ### end Alembic commands ###
