"""stats update

Revision ID: e97b3c7878f2
Revises: b9314ab2b82f
Create Date: 2026-07-09 08:54:07.896996

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e97b3c7878f2'
down_revision = 'b9314ab2b82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
