"""succes field report

Revision ID: fd7e460d2f8d
Revises: cf619a82741d
Create Date: 2026-07-20 11:06:13.483219

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fd7e460d2f8d'
down_revision = 'cf619a82741d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
